[package]
name = "backend"
version = "0.1.0"
authors = ["Julien SENON <julien.senon@gmail.com>"]
edition = "2018"

[dependencies]
iron = "0.6.0"
router = "0.6.0"
serde = "1.0.85"
serde_json = "1.0.38"
serde_derive = "1.0.85"
trackable = "0.2.21"
rustracing = "0.1.8"
rustracing_jaeger = "0.1.9"